name: ci

on: [push]

jobs:
  ci_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "16.13.1"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm dependencies
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint
      - name: Run stylelint
        run: yarn slint
      - name: Run prettier
        run: yarn format
      - name: Run test
        run: yarn test
      - uses: actions/upload-artifact@v2
        with:
          name: coverage_jest
          path: coverage
